/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author feña
 */
public class Operacion extends javax.swing.JFrame {

    /**
     * Creates new form Operacion
     */
    public Operacion() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle(" Operacion ");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton2.setText("ramos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("profesores(a)");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("ver notas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("salas");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton5))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         String respuest10 = JOptionPane.showInputDialog("Introduzca Rut");
       String respuest11 = JOptionPane.showInputDialog("Introduzca Monto a Retirar");
       
       	try
    		{
    		
    		
            DriverManager.registerDriver(new org.gjt.mm.mysql.Driver());
            
            
            Connection con43 = DriverManager.getConnection (
                "jdbc:mysql://localhost/redbanc","root", "root");
            
           
            Statement scon43 = con43.createStatement();
            
            
            //primero consulta
             ResultSet rests 	=scon43.executeQuery("select montototal  from cuentacorriente  where Rut_Cliente= '"+respuest10+"'");
            int valor=0;
            while(rests.next())
            {
                 
            
           	      
        		 valor=rests.getInt("MontoTotal")-Integer.parseInt(respuest11);
        			
           	
             }
            if(valor>=0)
            {
            scon43.executeUpdate("UPDATE cuentacorriente  set MontoTotal = "+valor+" WHERE Rut_Cliente= "+respuest10);
         JOptionPane.showMessageDialog(null,
   "Retiro Exitoso");
            }
            else
            {
                JOptionPane.showMessageDialog(null,
   "Saldo Insuficiente");
            } 	
    	     
            
    		
    			 
                	scon43.close();
    			
    		}
    	 
    		 
    		catch(Exception sadv)
    		{
    			
    		}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String respuest14 = JOptionPane.showInputDialog("Introduzca su Rut");
       String respuest15 = JOptionPane.showInputDialog("Introduzca Monto a Transferir");
       String respuest16 = JOptionPane.showInputDialog("Introduzca Rut del beneficiario");
       try
    		{
    		
    		
            DriverManager.registerDriver(new org.gjt.mm.mysql.Driver());
            
     
            Connection con45 = DriverManager.getConnection (
                "jdbc:mysql://localhost/redbanc","root", "root");
            
            
            Statement scon45 = con45.createStatement();
            
            
            //primero consulta
             ResultSet rests 	=scon45.executeQuery("select MontoTotal  from cuentacorriente  where Rut_Cliente= "+respuest16);
            int valor2=0;
            while(rests.next())
            {
                 
            
           	      
        		 valor2= rests.getInt("MontoTotal")+Integer.parseInt(respuest15);
        			
           	
             } 
              	
    	 scon45.executeUpdate("UPDATE cuentacorriente  set MontoTotal = "+valor2+" WHERE Rut_Cliente= "+respuest16);
          
           	scon45.close();
        
    		
    			 
               
                	
                		try
    		{
    		
    		
            DriverManager.registerDriver(new org.gjt.mm.mysql.Driver());
            
          
            Connection con50 = DriverManager.getConnection (
                "jdbc:mysql://localhost/redbanc","root", "root");
            
           
            Statement scon50 = con50.createStatement();
            
            
            
             ResultSet r 	=scon50.executeQuery("select MontoTotal  from cuentacorriente  where Rut_Cliente= "+respuest14);
            int valor0=0;
            while(r.next())
            {
                 
            
           	      
        		 valor0= rests.getInt("MontoTotal")-Integer.parseInt(respuest15);
        			
           	
             } 
              	
    	 scon50.executeUpdate("UPDATE cuentacorriente  set MontoTotal = "+valor0+" WHERE Rut_Cliente=  "+respuest14);
               
    		
    			 
                	scon50.close();
    			
    		}
    	 
    		 
    		catch(Exception sadv)
    		{
    			
    		}
    			
    		}
    	 
    		 
    		catch(Exception sadv)
    		{
    			
    		}
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String respuest12 = JOptionPane.showInputDialog("Introduzca Rut");
       String respuest13 = JOptionPane.showInputDialog("Introduzca Monto a Depositar");
       try
    		{
    		
    		
            DriverManager.registerDriver(new org.gjt.mm.mysql.Driver());
            
          
            Connection con44 = DriverManager.getConnection (
                "jdbc:mysql://localhost/redbanc","root", "root");
            
            
            Statement scon44 = con44.createStatement();
            
            
            //primero consulta
             ResultSet rests 	=scon44.executeQuery("select MontoTotal  from cuentacorriente  where Rut_Cliente= "+respuest12);
            int valor1=0;
            while(rests.next())
            {
                 
            
           	      
        		 valor1= rests.getInt("MontoTotal")+Integer.parseInt(respuest13);
        			
           	
             } 
              	
    	 scon44.executeUpdate("UPDATE cuentacorriente  set MontoTotal = "+valor1+" WHERE Rut_Cliente= "+respuest12);
            JOptionPane.showMessageDialog(null,
   "Deposito Exitoso");
            
            	     
    		
    			 
                	scon44.close();
    			
    		}
    	 
    		 
    		catch(Exception sadv)
    		{
    			
    		}
       
        
          	
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          String respuest10 = JOptionPane.showInputDialog("Introduzca Rut");
       
    
       	try
    		{
    		
    		
            DriverManager.registerDriver(new org.gjt.mm.mysql.Driver());
            
     
            Connection con43 = DriverManager.getConnection (
                "jdbc:mysql://localhost/redbanc","root", "root");
            
           
            Statement scon43 = con43.createStatement();
            
            
           
             ResultSet rests 	=scon43.executeQuery("select montototal  from cuentacorriente  where Rut_Cliente= '"+respuest10+"'");
            while(rests.next())
            {
              JOptionPane.showMessageDialog(null,
   "Saldo:"+rests.getInt("MontoTotal"));
              
            }
            
          
             	
    	     
            
    		
    			 
                	scon43.close();
    			
    		}
    	 
    		 
    		catch(Exception sadv)
    		{
    			
    		}
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Operacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Operacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Operacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Operacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Operacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
